# Generated by Django 4.1.2 on 2022-10-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('fam', models.TextField()),
                ('name', models.TextField()),
                ('otc', models.TextField()),
            ],
        ),
    ]
